# Use Node.js base image
FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (to install dependencies)
COPY package*.json ./

# Install backend dependencies (express)
RUN npm install

# Copy backend code
COPY ./server ./server

# Copy the 'dist' folder that was generated by Vite's build process
COPY ./dist ./dist

# Expose the required port for the backend
EXPOSE 3000

# Command to run the backend
CMD ["node", "server/index.js"]
