services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - "3000:3000" # Backend (Express)
      volumes:
         - ./node_modules:/app/node_modules # Sync node_modules
         - ./server:/app/server # Sync backend code
      environment:
         - VITE_API_URL=${VITE_API_URL:-http://localhost:3000} # Default to localhost in dev
      command: "node server/index.js" # Only run the backend
      networks:
         - gog-threejs-app_network

networks:
   gog-threejs-app_network:
      name: gog-threejs-app_default # This ensures the correct label is applied to the network
